---
- name: update firewalld for http and https
  firewalld: immediate=yes permanent=yes service={{ item }} state=enabled
  with_items:
    - http
    - https

- name: set selinux flag to let httpd connect to workers
  seboolean: name=httpd_can_network_connect persistent=yes state=yes
  
- name: add mod_proxy configuration
  template: src=proxy.conf.j2 dest=/etc/httpd/conf.d/proxy.conf
  notify:
    - enable and restart httpd
